### PR TITLE
feat: adds teleport lines & pads (assets pending)

### PR DESCRIPTION
**Pull request by danhannigan**
Connected to #8

- Adds new teleport pad locations
- Adds new teleport line locations

Pending on assets for teleport pads, just using the x mark for now. 

Screenshot 2022-10-06 at 10 29 26 AM

### CODE REVIEW

**Comment by Clearmist** [comment]
Thanks, Dan! That was fast!

**Comment by BrookJeynes** [comment]
@danhannigan looking good, I'll add the assets later today then I'll merge :)

**Comment by danhannigan** [comment]
Right on! Tangential but I noticed that my own vscode / prettier settings likely did some formatting updates. Might look into a prettierrc or editorconfig just so we don't keep getting commits that are bigger than they need to be

**Comment by danhannigan** [comment]
@BrookJeynes I briefly looked into that! There is a bezier curve plugin for it that I was debating digging into; I could spend a bit more time seeing if that would work (also possibly a gradient background like it is in the actual map, too): https://github.com/elfalem/Leaflet.curve

http://elfalem.github.io/Leaflet.curve/ here's a demo link

**Comment by BrookJeynes** [comment]
@danhannigan I'm happy to take a look later when I merge in the assets. I'll let you know if I need any help :)

**Comment by BrookJeynes** [comment]
@danhannigan Just added the library and seems to work great. I unfortunately don't have the in-game map in-front of me so I can't make the curves how they are in game. Did you want to give that a shot? 

I left some comments in `TeleportLine.jsx` but I'll rephrase here:
- The math I'm using (taken from an article) does not work for our needs but still works as a placeholder. Will most likely need to calculate/guestimate the middle curve point ourselves based off the in-game map
- Due to the way the lines are now being added via `.addTo(map)`, it may make more sense to not have `TeleportLine.jsx` as a component? Let me know what you think

**Comment by danhannigan** [comment]
@BrookJeynes oh rad! yeah I can pull it down and see how far I can get with the curves. And yeah, I think dropping TeleportLine.jsx makes sense.

**Comment by BrookJeynes** [comment]
@danhannigan I tried to find a React variant for the library but the only one I could see was out-of-date so I had to do it the `.addTo(map)` way :/

**Comment by danhannigan** [comment]
@BrookJeynes ah gotcha, that's okay, at least it works!  In looking at this I'm thinking adding an additional point to the line data that is our midpoint might work best, or at least it'd give us the most predictable outcome

**Comment by danhannigan** [comment]
Screenshot 2022-10-06 at 3 23 24 PM
Screenshot 2022-10-06 at 3 23 40 PM
Screenshot 2022-10-06 at 3 23 50 PM

Here's a quick example with custom input midpoints @BrookJeynes

**Comment by BrookJeynes** [comment]
@danhannigan Looks great, doing by hand should be fine. I can't image the map lines changing in future updates and if so there's only like 5 in total.

**Comment by danhannigan** [comment]
@BrookJeynes kicked up some updates, I also adjusted the line visuals slightly (width and stroke) to be more like dots, like the actual map.

**Comment by BrookJeynes** [comment]
@danhannigan Perfect, I'll fix the merge conflicts and add in the map asset after work then merge this.

**Comment by danhannigan** [comment]
@BrookJeynes I was already in there goofin' with the merge conflict, I got it cleared up for ya

**Comment by BrookJeynes** [comment]
@danhannigan just created a new commit, decided not to go down the leaflet.curve way as this restricted us to using `.addTo(map)` which proved difficult when trying to make it work with the layer controls (to hide and show the lines). It's because of this that I'm now just using a Bezier curve algorithm to generate the coordinates and use those inside a Polyline component.

**Comment by danhannigan** [comment]
@BrookJeynes oh gotcha! Sounds like a good solve to me

**Pull request merged**
